apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
  labels:
    app: user-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: your-dockerhub-username/user-auth:latest # Replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgres://shaun:shaun@postgres-service:5432/wassupdb"
