apiVersion: apps/v1
kind: Deployment
metadata:
  name: wassup-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wassup
  template:
    metadata:
      labels:
        app: wassup
    spec:
      containers:
        - name: wassup
          image: your-dockerhub-username/wassup:latest
          ports:
            - containerPort: 5004
          env:
            - name: POSTGRES_CONN
              value: "postgres://shaun:shaun@postgres-service:5432/wassupdb"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: wassup-service
spec:
  selector:
    app: wassup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: ClusterIP
